# Generated by Django 3.0.8 on 2020-07-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
